// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/menu": {
    params: {};
  };
  "/pizza": {
    params: {};
  };
  "/burgers": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/.well-known/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/menu" | "/pizza" | "/burgers" | "/cart" | "/checkout" | "/orders" | "/.well-known/*";
  };
  "routes/landing.tsx": {
    id: "routes/landing";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/menu.tsx": {
    id: "routes/menu";
    page: "/menu";
  };
  "routes/pizza.tsx": {
    id: "routes/pizza";
    page: "/pizza";
  };
  "routes/burgers.tsx": {
    id: "routes/burgers";
    page: "/burgers";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/orders.tsx": {
    id: "routes/orders";
    page: "/orders";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/.well-known/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/landing": typeof import("./app/routes/landing.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/menu": typeof import("./app/routes/menu.tsx");
  "routes/pizza": typeof import("./app/routes/pizza.tsx");
  "routes/burgers": typeof import("./app/routes/burgers.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/checkout": typeof import("./app/routes/checkout.tsx");
  "routes/orders": typeof import("./app/routes/orders.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};